#region License

// Kraggs.Graphics.OpenGL (github.com/raggsokk)
//
// Copyright (c) 2013 Jarle Hansen (github.com/raggsokk)
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
// 
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
// THE SOFTWARE.

#endregion

using System;
using System.Collections.Generic;
using System.Text;

using System.Security;
using System.Diagnostics;
using System.Runtime.InteropServices;
using System.Runtime.CompilerServices;

namespace Kraggs.Graphics.OpenGL
{
    public enum GetParameters
    {
        ActiveTexture = All.ACTIVE_TEXTURE,
        AliasedLineWidthRange = All.ALIASED_LINE_WIDTH_RANGE,
        ArrayBufferBinding = All.ARRAY_BUFFER_BINDING,
        Blend = All.BLEND,
        //BlendColor = All.Blend_COLOR,
        BlendDstAlpha = All.BLEND_DST_ALPHA,
        BlendDstRgb = All.BLEND_DST_RGB,
        BlendEquationRgb = All.BLEND_EQUATION_RGB,
        BlendEquationAlpha = All.BLEND_EQUATION_ALPHA,
        BlendSrcAlpha = All.BLEND_SRC_ALPHA,
        BlendSrcRgb = All.BLEND_SRC_RGB,
        ColorClearValue = All.COLOR_CLEAR_VALUE,
        ColorLogicOp = All.COLOR_LOGIC_OP,
        ColorWriteMask = All.COLOR_WRITEMASK,
        CompressedTextureFormats = All.COMPRESSED_TEXTURE_FORMATS,
        MaxComputeShaderStorageBlocks = All.MAX_COMPUTE_SHADER_STORAGE_BLOCKS,
        MaxCombinedShaderStorageBlocks = All.MAX_COMBINED_SHADER_STORAGE_BLOCKS,
        MaxComputeUniformBlocks = All.MAX_COMPUTE_UNIFORM_BLOCKS,
        MaxComputeTextureImageUnits = All.MAX_COMPUTE_TEXTURE_IMAGE_UNITS,
        MaxComputeUniformComponents = All.MAX_COMPUTE_UNIFORM_COMPONENTS,
        MaxComputeAtomicCounters = All.MAX_COMPUTE_ATOMIC_COUNTERS,
        MaxComputeAtomicCounterBuffers = All.MAX_COMPUTE_ATOMIC_COUNTER_BUFFERS,
        MaxCombinedComputeUniformComponents = All.MAX_COMBINED_COMPUTE_UNIFORM_COMPONENTS,
        //MaxComputeWorkGroupInvocations = All.MAX_COMPUTE_WORK_GROUP_INVOCATIONS,
        MaxComputeWorkGroupCount = All.MAX_COMPUTE_WORK_GROUP_COUNT,
        MaxComputeWorkGroupSize = All.MAX_COMPUTE_WORK_GROUP_SIZE,
        DispatchIndirectBufferBinding = All.DISPATCH_INDIRECT_BUFFER_BINDING,
        MaxDebugGroupStackDepth = All.MAX_DEBUG_GROUP_STACK_DEPTH,
        DebugGroupStackDepth = All.DEBUG_GROUP_STACK_DEPTH,
        ContextFlags = All.CONTEXT_FLAGS,
        CullFace = All.CULL_FACE,
        CurrentProgram = All.CURRENT_PROGRAM,
        DepthClearValue = All.DEPTH_CLEAR_VALUE,
        DepthFunc = All.DEPTH_FUNC,
        DepthRange = All.DEPTH_RANGE,
        DepthTest = All.DEPTH_TEST,
        DepthWritemask = All.DEPTH_WRITEMASK,
        Dither = All.DITHER,
        DoubleBuffer = All.DOUBLEBUFFER,
        DrawBuffer = All.DRAW_BUFFER,
        DrawBuffer0 = All.DRAW_BUFFER0,
        DrawBuffer1 = All.DRAW_BUFFER1,
        DrawBuffer2 = All.DRAW_BUFFER2,
        DrawBuffer3 = All.DRAW_BUFFER3,
        DrawBuffer4 = All.DRAW_BUFFER4,
        DrawBuffer5 = All.DRAW_BUFFER5,
        DrawBuffer6 = All.DRAW_BUFFER6,
        DrawBuffer7 = All.DRAW_BUFFER7,
        DrawBuffer8 = All.DRAW_BUFFER8,
        DrawBuffer9 = All.DRAW_BUFFER9,
        DrawBuffer10 = All.DRAW_BUFFER10,
        DrawBuffer11 = All.DRAW_BUFFER11,
        DrawBuffer12 = All.DRAW_BUFFER12,
        DrawBuffer13 = All.DRAW_BUFFER13,
        DrawBuffer14 = All.DRAW_BUFFER14,
        DrawBuffer15 = All.DRAW_BUFFER15,
        DrawFramebufferBinding = All.DRAW_FRAMEBUFFER_BINDING,
        ReadFramebufferBinding = All.READ_FRAMEBUFFER_BINDING,
        ElementArrayBufferBinding = All.ELEMENT_ARRAY_BUFFER_BINDING,
        FragmentShaderDerivativeHint = All.FRAGMENT_SHADER_DERIVATIVE_HINT,
        ImplementationColorReadformat = All.IMPLEMENTATION_COLOR_READ_FORMAT,
        ImplementationColorReadType = All.IMPLEMENTATION_COLOR_READ_TYPE,
        LineSmooth = All.LINE_SMOOTH,
        LineSmoothHint = All.LINE_SMOOTH_HINT,
        LineWidth = All.LINE_WIDTH,
        LayerProvokingVertex = All.LAYER_PROVOKING_VERTEX,
        LineWidthGranularity = All.LINE_WIDTH_GRANULARITY,
        LineWidthRange = All.LINE_WIDTH_RANGE,
        LogicOpMode = All.LOGIC_OP_MODE,
        MajorVersion = All.MAJOR_VERSION,
        MaxTexture3DSize = All.MAX_3D_TEXTURE_SIZE,
        MaxTextureArrayLayers = All.MAX_ARRAY_TEXTURE_LAYERS,
        MaxClipDistance = All.MAX_CLIP_DISTANCES,
        MaxColorTextureSamples = All.MAX_COLOR_TEXTURE_SAMPLES,
        MaxCombinedAtomicCounters = All.MAX_COMBINED_ATOMIC_COUNTERS,
        MaxCombinedFragmentUniformComponents = All.MAX_COMBINED_FRAGMENT_UNIFORM_COMPONENTS,
        //MaxCombinedGeometryUniformComponents = All.MAX_COMBINED_GEOMETRY_UNIFORM_COMPONENTS,
        MaxCombinedTextureImageUnits = All.MAX_COMBINED_TEXTURE_IMAGE_UNITS,
        MaxCombinedUniformBlocks = All.MAX_COMBINED_UNIFORM_BLOCKS,
        MaxCombinedVertexUniformComponents = All.MAX_COMBINED_VERTEX_UNIFORM_COMPONENTS,
        MaxTextureCubemapSize = All.MAX_CUBE_MAP_TEXTURE_SIZE,
        MaxTextureDepthSamples = All.MAX_DEPTH_TEXTURE_SAMPLES,
        MaxDrawBuffers = All.MAX_DRAW_BUFFERS,
        MaxDualSourceDrawBuffers = All.MAX_DUAL_SOURCE_DRAW_BUFFERS,
        MaxElementsIndices = All.MAX_ELEMENTS_INDICES,
        MaxElementsVertices = All.MAX_ELEMENTS_VERTICES,
        MaxFragmentAtomicCounters = All.MAX_FRAGMENT_ATOMIC_COUNTERS,
        MaxFragmentShaderStorageBlocks = All.MAX_FRAGMENT_SHADER_STORAGE_BLOCKS,
        MaxFragmentInputComponents = All.MAX_FRAGMENT_INPUT_COMPONENTS,
        MaxFragmentUniformComponents = All.MAX_FRAGMENT_UNIFORM_COMPONENTS,
        MaxFragmentUniformVectors = All.MAX_FRAGMENT_UNIFORM_VECTORS,
        MaxFragmentUniformBlocks = All.MAX_FRAGMENT_UNIFORM_BLOCKS,
        MaxFramebufferWidth = All.MAX_FRAMEBUFFER_WIDTH,
        MaxFramebufferHeight = All.MAX_FRAMEBUFFER_HEIGHT,
        MaxFramebufferLayers = All.MAX_FRAMEBUFFER_LAYERS,
        MaxFramebufferSamples = All.MAX_FRAMEBUFFER_SAMPLES,
        MaxGeometryAtomicCounters = All.MAX_GEOMETRY_ATOMIC_COUNTERS,
        MaxGeometryShaderStorageBlocks = All.MAX_GEOMETRY_SHADER_STORAGE_BLOCKS,
        MaxGeometryInputComponents = All.MAX_GEOMETRY_INPUT_COMPONENTS,
        MaxGeometryOutputComponents = All.MAX_GEOMETRY_OUTPUT_COMPONENTS,
        MaxGeometryTextureImageUnits = All.MAX_GEOMETRY_TEXTURE_IMAGE_UNITS,
        //MaxGeometryUniformBlocks = All.MAX_GEOMETRY_UNIFORM_BLOCKS,
        MaxGeometryUniformComponents = All.MAX_GEOMETRY_UNIFORM_COMPONENTS,
        MaxIntegerSamples = All.MAX_INTEGER_SAMPLES,
        MinMapBufferAlignment = All.MIN_MAP_BUFFER_ALIGNMENT,
        MaxLabelLength = All.MAX_LABEL_LENGTH,
        MaxProgramTexelOffset = All.MAX_PROGRAM_TEXEL_OFFSET,
        MinProgramTexelOffset = All.MIN_PROGRAM_TEXEL_OFFSET,
        MaxTextureRectangeSize = All.MAX_RECTANGLE_TEXTURE_SIZE,
        MaxRenderbufferSize = All.MAX_RENDERBUFFER_SIZE,
        MaxSampleMaskWords = All.MAX_SAMPLE_MASK_WORDS,
        MaxServerWaitTimout = All.MAX_SERVER_WAIT_TIMEOUT,
        MaxShaderStorageBufferBindings = All.MAX_SHADER_STORAGE_BUFFER_BINDINGS,
        MaxTessControlAtomicCounters = All.MAX_TESS_CONTROL_ATOMIC_COUNTERS,
        MaxTessEvaluationAtomicCounters = All.MAX_TESS_EVALUATION_ATOMIC_COUNTERS,
        MaxTessControlShaderStorageBlocks = All.MAX_TESS_CONTROL_SHADER_STORAGE_BLOCKS,
        MaxTessEvaluationShaderStorageBlocks = All.MAX_TESS_EVALUATION_SHADER_STORAGE_BLOCKS,
        MaxTextureBufferSize = All.MAX_TEXTURE_BUFFER_SIZE,
        MaxTextureImageUnits = All.MAX_TEXTURE_IMAGE_UNITS,
        MaxTextureLodBias = All.MAX_TEXTURE_LOD_BIAS,
        MaxTextureSize = All.MAX_TEXTURE_SIZE,
        MaxUniformBufferBindings = All.MAX_UNIFORM_BUFFER_BINDINGS,
        MaxUniformBlockSize = All.MAX_UNIFORM_BLOCK_SIZE,
        MaxUniformLocations = All.MAX_UNIFORM_LOCATIONS,
        MaxVaryingComponents = All.MAX_VARYING_COMPONENTS,
        MaxVaryingVectors = All.MAX_VARYING_VECTORS,
        MaxVaryingFloats = All.MAX_VARYING_FLOATS,
        MaxVertexAtomicCounters = All.MAX_VERTEX_ATOMIC_COUNTERS,
        MaxVertexAttribs = All.MAX_VERTEX_ATTRIBS,
        MaxVertexShaderStorageBlocks = All.MAX_VERTEX_SHADER_STORAGE_BLOCKS,
        MaxVertexTextureImageUnits = All.MAX_VERTEX_TEXTURE_IMAGE_UNITS,
        MaxVertexUniformComponents = All.MAX_VERTEX_UNIFORM_COMPONENTS,
        MaxVertexUniformVectors = All.MAX_VERTEX_UNIFORM_VECTORS,
        MaxVertexOutputComponents = All.MAX_VERTEX_OUTPUT_COMPONENTS,
        MaxVertexUniformBlocks = All.MAX_VERTEX_UNIFORM_BLOCKS,
        MaxViewportDimensions = All.MAX_VIEWPORT_DIMS,
        MaxViewports = All.MAX_VIEWPORTS,
        MinorVersion = All.MINOR_VERSION,
        NumCompressedTextureFormats = All.NUM_COMPRESSED_TEXTURE_FORMATS,
        NumExtensions = All.NUM_EXTENSIONS,
        NumProgramBinaryFormats = All.NUM_PROGRAM_BINARY_FORMATS,
        NumShaderBinaryFormats = All.NUM_SHADER_BINARY_FORMATS,
        PackAlignment = All.PACK_ALIGNMENT,
        PackImageHeight = All.PACK_IMAGE_HEIGHT,
        PackLsbFirst = All.PACK_LSB_FIRST,
        PackRowLength = All.PACK_ROW_LENGTH,
        PackSkipImages = All.PACK_SKIP_IMAGES,
        PackSkipPixels = All.PACK_SKIP_PIXELS,
        PackSkipRows = All.PACK_SKIP_ROWS,
        PackSwapBytes = All.PACK_SWAP_BYTES,
        PixelPackBufferBinding = All.PIXEL_PACK_BUFFER_BINDING,
        PixelUnpackBufferBinding = All.PIXEL_UNPACK_BUFFER_BINDING,
        PointFadeThresholdSize = All.POINT_FADE_THRESHOLD_SIZE,
        PrimitiveRestartIndex = All.PRIMITIVE_RESTART_INDEX,
        ProgramBinaryFormats = All.PROGRAM_BINARY_FORMATS,
        ProgramPipelineBinding = All.PROGRAM_PIPELINE_BINDING,
        ProvokingVertex = All.PROVOKING_VERTEX,
        PointSize = All.POINT_SIZE,
        PointSizeGranularity = All.POINT_SIZE_GRANULARITY,
        PointSizeRange = All.POINT_SIZE_RANGE,
        PolygonOffsetFactor = All.POLYGON_OFFSET_FACTOR,
        PolygonOffsetUnits = All.POLYGON_OFFSET_UNITS,
        PolygonOffsetFill = All.POLYGON_OFFSET_FILL,
        PolygonOffsetLine = All.POLYGON_OFFSET_LINE,
        PolygonOffsetPoint = All.POLYGON_OFFSET_POINT,
        PolygonSmooth = All.POLYGON_SMOOTH,
        PolygonSmoothHint = All.POLYGON_SMOOTH_HINT,
        ReadBuffer = All.READ_BUFFER,
        RenderbufferBinding = All.RENDERBUFFER_BINDING,
        SampleBuffers = All.SAMPLE_BUFFERS,
        SampleCoverageValue = All.SAMPLE_COVERAGE_VALUE,
        SampleCoverageInvert = All.SAMPLE_COVERAGE_INVERT,
        SamplerBinding = All.SAMPLER_BINDING,
        Samples = All.SAMPLES,
        ScissorBox = All.SCISSOR_BOX,
        ScissorTest = All.SCISSOR_TEST,
        ShaderCompiler = All.SHADER_COMPILER,
        ShaderStorageBufferBinding = All.SHADER_STORAGE_BUFFER_BINDING,
        ShaderStorageBufferOffsetAlignment = All.SHADER_STORAGE_BUFFER_OFFSET_ALIGNMENT,
        ShaderStorageBufferStart = All.SHADER_STORAGE_BUFFER_START,
        ShaderStorageBufferSize = All.SHADER_STORAGE_BUFFER_SIZE,
        SmoothLineWidthRange = All.SMOOTH_LINE_WIDTH_RANGE,
        SmoothLineWidthGranularity = All.SMOOTH_LINE_WIDTH_GRANULARITY,
        StencilBackFail = All.STENCIL_BACK_FAIL,
        StencilBackFunc = All.STENCIL_BACK_FUNC,
        StencilBackPassDepthFail = All.STENCIL_BACK_PASS_DEPTH_FAIL,
        StencilBackPassDepthPass = All.STENCIL_BACK_PASS_DEPTH_PASS,
        StencilBackRef = All.STENCIL_BACK_REF,
        StencilBackValueMask = All.STENCIL_BACK_VALUE_MASK,
        StencilBackWriteMask = All.STENCIL_BACK_WRITEMASK,
        StencilClearValue = All.STENCIL_CLEAR_VALUE,
        StencilFail = All.STENCIL_FAIL,
        StencilFunc = All.STENCIL_FUNC,
        StencilPassDepthFail = All.STENCIL_PASS_DEPTH_FAIL,
        StencilPassDepthPass = All.STENCIL_PASS_DEPTH_PASS,
        StencilRef = All.STENCIL_REF,
        StencilTest = All.STENCIL_TEST,
        StencilValueMask = All.STENCIL_VALUE_MASK,
        StencilWriteMask = All.STENCIL_WRITEMASK,
        Stereo = All.STEREO,
        SubPixelBits = All.SUBPIXEL_BITS,
        TextureBinding1D = All.TEXTURE_BINDING_1D,
        TextureBinding1DArray = All.TEXTURE_BINDING_1D_ARRAY,
        TextureBinding2D = All.TEXTURE_BINDING_2D,
        TextureBinding2DArray = All.TEXTURE_BINDING_2D_ARRAY,
        TextureBinding2DMultiSample = All.TEXTURE_BINDING_2D_MULTISAMPLE,
        TextureBinding2DMultiSampleArray = All.TEXTURE_BINDING_2D_MULTISAMPLE_ARRAY,
        TextureBinding3D = All.TEXTURE_BINDING_3D,
        TextureBindingBuffer = All.TEXTURE_BINDING_BUFFER,
        TextureBindingCubeMap = All.TEXTURE_BINDING_CUBE_MAP,
        TextureBindingRectangle = All.TEXTURE_BINDING_RECTANGLE,
        TextureBindingCubeMapArray = All.TEXTURE_BINDING_CUBE_MAP_ARRAY,
        TextureCompressionHint = All.TEXTURE_COMPRESSION_HINT,
        //TextureBufferBinding = All.texture_buffer_BINDING
        TextureBufferDataStoreBinding = All.TEXTURE_BUFFER_DATA_STORE_BINDING,
        TextureBufferOffsetAlignment = All.TEXTURE_BUFFER_OFFSET_ALIGNMENT,
        Timestamp = All.TIMESTAMP,
        TransformFeedbackBufferBinding = All.TRANSFORM_FEEDBACK_BUFFER_BINDING,
        TransformFeedbackBufferStart = All.TRANSFORM_FEEDBACK_BUFFER_START,
        TransformFeedbackBufferSize = All.TRANSFORM_FEEDBACK_BUFFER_SIZE,
        UniformBufferBinding = All.UNIFORM_BUFFER_BINDING,
        UniformBufferOffsetAlignment = All.UNIFORM_BUFFER_OFFSET_ALIGNMENT,
        UniformBufferStart = All.UNIFORM_BUFFER_START,
        UnpackAlignment = All.UNPACK_ALIGNMENT,
        UnpackImageHeight = All.UNPACK_IMAGE_HEIGHT,
        UnpackLsbFirst = All.UNPACK_LSB_FIRST,
        UnpackRowLength = All.UNPACK_ROW_LENGTH,
        UnpackSkipImages = All.UNPACK_SKIP_IMAGES,
        UnpackSkipPixels = All.UNPACK_SKIP_PIXELS,
        UnpackSkipRows = All.UNPACK_SKIP_ROWS,
        UnpackSwapBytes = All.UNPACK_SWAP_BYTES,
        VertexArrayBinding = All.VERTEX_ARRAY_BINDING,
        VertexProgramPointSize = All.VERTEX_PROGRAM_POINT_SIZE,
        VertexBindingDivisor = All.VERTEX_BINDING_DIVISOR,
        VertexBindingOffset = All.VERTEX_BINDING_OFFSET,
        VertexBindingStride = All.VERTEX_BINDING_STRIDE,
        MaxVertexAttribRelativeOffset = All.MAX_VERTEX_ATTRIB_RELATIVE_OFFSET,
        MaxVertexAttribBindings = All.MAX_VERTEX_ATTRIB_BINDINGS,
        Viewport = All.VIEWPORT,
        ViewportBoundsRange = All.VIEWPORT_BOUNDS_RANGE,
        ViewportIndexProvokingVertex = All.VIEWPORT_INDEX_PROVOKING_VERTEX,
        ViewportSubPixelBits = All.VIEWPORT_SUBPIXEL_BITS,
        MaxElementIndex = All.MAX_ELEMENT_INDEX,

        QueryBufferBinding = All.QUERY_BUFFER_BINDING,










        // some hacks?!
        MaxIndicesSize = MaxElementsIndices,
        MaxIndicesVertices = MaxElementsVertices,
        IndicesArrayBufferBinding = ElementArrayBufferBinding,
    }
}
